import type { Metadata } from "next";
import "./globals.css";
import Title from "@/components/Title";

export const metadata: Metadata = {
  title: "Next Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <header>
          <Title />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
